In [1]:
# %pip install -r ../requirements.txt

In [1]:
import pandas as pd, numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#load the data from this path 'C:\Users\jubril\Desktop\Projects\ML\Spam Classifier\spam-classifier\data\raw\SMSSpamCollection' and assign it to a dataframe called df. The data is tab separated and has no header. The first column is the label and the second column is the message. Assign the column names to be 'label' and 'message'.    
df = pd.read_csv(r'..\data\raw\SMSSpamCollection', sep='\t', header=None, names=['v1', 'v2']
                 )
#check the first 5 rows of the dataframe
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [4]:
df.rename(columns={'v1':'target', 'v2':'message'}, inplace=True)
df['target'] = df['target'].map({'ham':0, 'spam':1})
# drop duplicates
df.drop_duplicates(keep='first', inplace=True)
df.head()

   target                                            message
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [5]:
df['target'].value_counts()

target
0    4516
1     653
Name: count, dtype: int64

In [6]:
# Implement at least 3 Python assert statements to validate your data
assert df['message'].dtype == object, "Message column should be of type object" 
assert df['target'].dtype == np.int64, "Target column should be of type int64"
assert df['target'].nunique() == 2, "Target column should have exactly 2 unique values"
assert df.isnull().sum().sum() == 0, "Dataframe should not contain any null values"
assert df.duplicated().sum() == 0, "Dataframe should not contain any duplicate rows"

In [8]:
# Initialize a simple text vectorizer (e.g., TfidfVectorizer or CountVectorizer from scikit-learn).
# Create a function build_pipeline(X_train) that fits and returns the full transformation pipeline (Vectorizers, Scalers, etc.).)
def build_pipeline(X_train):
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler

    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer()),
        ('scaler', StandardScaler(with_mean=False))
    ])
    
    pipeline.fit(X_train)
    return pipeline

In [9]:


df.iloc[:1].to_numpy()

array([[0,
        'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']],
      dtype=object)